# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bank.proto',
  package='bank',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nbank.proto\x12\x04\x62\x61nk\"0\n\x0e\x64\x65positRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"E\n\x0c\x64\x65positReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\r\x12\x13\n\x0brecordIndex\x18\x03 \x01(\r\"3\n\x11withdrawalRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"H\n\x0fwithdrawalReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\r\x12\x13\n\x0brecordIndex\x18\x03 \x01(\r\"!\n\x0e\x62\x61lanceRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\"0\n\x0c\x62\x61lanceReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\r\"H\n\x0ftransferRequest\x12\x13\n\x0b\x66romAccount\x18\x01 \x01(\t\x12\x11\n\ttoAccount\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\r\"F\n\rtransferReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\r\x12\x13\n\x0brecordIndex\x18\x03 \x01(\r\"#\n\x10getRecordRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\"g\n\x0egetRecordReply\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x11\n\toperation\x18\x03 \x01(\r\x12\x14\n\x0cotherAccount\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\r2\xad\x02\n\x04\x62\x61nk\x12\x35\n\x07\x64\x65posit\x12\x14.bank.depositRequest\x1a\x12.bank.depositReply\"\x00\x12>\n\nwithdrawal\x12\x17.bank.withdrawalRequest\x1a\x15.bank.withdrawalReply\"\x00\x12\x35\n\x07\x62\x61lance\x12\x14.bank.balanceRequest\x1a\x12.bank.balanceReply\"\x00\x12\x38\n\x08transfer\x12\x15.bank.transferRequest\x1a\x13.bank.transferReply\"\x00\x12=\n\tgetRecord\x12\x16.bank.getRecordRequest\x1a\x14.bank.getRecordReply\"\x00\x30\x01\x62\x06proto3')
)




_DEPOSITREQUEST = _descriptor.Descriptor(
  name='depositRequest',
  full_name='bank.depositRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='bank.depositRequest.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='bank.depositRequest.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=68,
)


_DEPOSITREPLY = _descriptor.Descriptor(
  name='depositReply',
  full_name='bank.depositReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='bank.depositReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='bank.depositReply.balance', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recordIndex', full_name='bank.depositReply.recordIndex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=139,
)


_WITHDRAWALREQUEST = _descriptor.Descriptor(
  name='withdrawalRequest',
  full_name='bank.withdrawalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='bank.withdrawalRequest.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='bank.withdrawalRequest.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=192,
)


_WITHDRAWALREPLY = _descriptor.Descriptor(
  name='withdrawalReply',
  full_name='bank.withdrawalReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='bank.withdrawalReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='bank.withdrawalReply.balance', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recordIndex', full_name='bank.withdrawalReply.recordIndex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=266,
)


_BALANCEREQUEST = _descriptor.Descriptor(
  name='balanceRequest',
  full_name='bank.balanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='bank.balanceRequest.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=301,
)


_BALANCEREPLY = _descriptor.Descriptor(
  name='balanceReply',
  full_name='bank.balanceReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='bank.balanceReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='bank.balanceReply.balance', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=351,
)


_TRANSFERREQUEST = _descriptor.Descriptor(
  name='transferRequest',
  full_name='bank.transferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromAccount', full_name='bank.transferRequest.fromAccount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toAccount', full_name='bank.transferRequest.toAccount', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='bank.transferRequest.value', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=425,
)


_TRANSFERREPLY = _descriptor.Descriptor(
  name='transferReply',
  full_name='bank.transferReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='bank.transferReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='bank.transferReply.balance', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recordIndex', full_name='bank.transferReply.recordIndex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=497,
)


_GETRECORDREQUEST = _descriptor.Descriptor(
  name='getRecordRequest',
  full_name='bank.getRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='bank.getRecordRequest.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=534,
)


_GETRECORDREPLY = _descriptor.Descriptor(
  name='getRecordReply',
  full_name='bank.getRecordReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='bank.getRecordReply.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='bank.getRecordReply.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operation', full_name='bank.getRecordReply.operation', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='otherAccount', full_name='bank.getRecordReply.otherAccount', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='bank.getRecordReply.value', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=639,
)

DESCRIPTOR.message_types_by_name['depositRequest'] = _DEPOSITREQUEST
DESCRIPTOR.message_types_by_name['depositReply'] = _DEPOSITREPLY
DESCRIPTOR.message_types_by_name['withdrawalRequest'] = _WITHDRAWALREQUEST
DESCRIPTOR.message_types_by_name['withdrawalReply'] = _WITHDRAWALREPLY
DESCRIPTOR.message_types_by_name['balanceRequest'] = _BALANCEREQUEST
DESCRIPTOR.message_types_by_name['balanceReply'] = _BALANCEREPLY
DESCRIPTOR.message_types_by_name['transferRequest'] = _TRANSFERREQUEST
DESCRIPTOR.message_types_by_name['transferReply'] = _TRANSFERREPLY
DESCRIPTOR.message_types_by_name['getRecordRequest'] = _GETRECORDREQUEST
DESCRIPTOR.message_types_by_name['getRecordReply'] = _GETRECORDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

depositRequest = _reflection.GeneratedProtocolMessageType('depositRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEPOSITREQUEST,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.depositRequest)
  ))
_sym_db.RegisterMessage(depositRequest)

depositReply = _reflection.GeneratedProtocolMessageType('depositReply', (_message.Message,), dict(
  DESCRIPTOR = _DEPOSITREPLY,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.depositReply)
  ))
_sym_db.RegisterMessage(depositReply)

withdrawalRequest = _reflection.GeneratedProtocolMessageType('withdrawalRequest', (_message.Message,), dict(
  DESCRIPTOR = _WITHDRAWALREQUEST,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.withdrawalRequest)
  ))
_sym_db.RegisterMessage(withdrawalRequest)

withdrawalReply = _reflection.GeneratedProtocolMessageType('withdrawalReply', (_message.Message,), dict(
  DESCRIPTOR = _WITHDRAWALREPLY,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.withdrawalReply)
  ))
_sym_db.RegisterMessage(withdrawalReply)

balanceRequest = _reflection.GeneratedProtocolMessageType('balanceRequest', (_message.Message,), dict(
  DESCRIPTOR = _BALANCEREQUEST,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.balanceRequest)
  ))
_sym_db.RegisterMessage(balanceRequest)

balanceReply = _reflection.GeneratedProtocolMessageType('balanceReply', (_message.Message,), dict(
  DESCRIPTOR = _BALANCEREPLY,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.balanceReply)
  ))
_sym_db.RegisterMessage(balanceReply)

transferRequest = _reflection.GeneratedProtocolMessageType('transferRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERREQUEST,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.transferRequest)
  ))
_sym_db.RegisterMessage(transferRequest)

transferReply = _reflection.GeneratedProtocolMessageType('transferReply', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERREPLY,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.transferReply)
  ))
_sym_db.RegisterMessage(transferReply)

getRecordRequest = _reflection.GeneratedProtocolMessageType('getRecordRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETRECORDREQUEST,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.getRecordRequest)
  ))
_sym_db.RegisterMessage(getRecordRequest)

getRecordReply = _reflection.GeneratedProtocolMessageType('getRecordReply', (_message.Message,), dict(
  DESCRIPTOR = _GETRECORDREPLY,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.getRecordReply)
  ))
_sym_db.RegisterMessage(getRecordReply)



_BANK = _descriptor.ServiceDescriptor(
  name='bank',
  full_name='bank.bank',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=642,
  serialized_end=943,
  methods=[
  _descriptor.MethodDescriptor(
    name='deposit',
    full_name='bank.bank.deposit',
    index=0,
    containing_service=None,
    input_type=_DEPOSITREQUEST,
    output_type=_DEPOSITREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='withdrawal',
    full_name='bank.bank.withdrawal',
    index=1,
    containing_service=None,
    input_type=_WITHDRAWALREQUEST,
    output_type=_WITHDRAWALREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='balance',
    full_name='bank.bank.balance',
    index=2,
    containing_service=None,
    input_type=_BALANCEREQUEST,
    output_type=_BALANCEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='transfer',
    full_name='bank.bank.transfer',
    index=3,
    containing_service=None,
    input_type=_TRANSFERREQUEST,
    output_type=_TRANSFERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getRecord',
    full_name='bank.bank.getRecord',
    index=4,
    containing_service=None,
    input_type=_GETRECORDREQUEST,
    output_type=_GETRECORDREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANK)

DESCRIPTOR.services_by_name['bank'] = _BANK

# @@protoc_insertion_point(module_scope)
